// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Gen_tz from "./gen_tz.bs.js";
import * as $$String from "bs-platform/lib/es6/string.js";
import * as Tea_html from "bucklescript-tea/src-ocaml/tea_html.js";

function labeled_input(label_name, attrs) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("labeledInput"),
              /* [] */0
            ], /* :: */[
              Tea_html.label(undefined, undefined, /* :: */[
                    Tea_html.for$prime(label_name),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.text(label_name),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.input$prime(undefined, undefined, /* :: */[
                      Tea_html.name(label_name),
                      attrs
                    ], /* [] */0),
                /* [] */0
              ]
            ]);
}

function labeled_select(select_name, options) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("labeledInput"),
              /* [] */0
            ], /* :: */[
              Tea_html.label(undefined, undefined, /* :: */[
                    Tea_html.for$prime(select_name),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.text(select_name),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.select(undefined, undefined, /* :: */[
                      Tea_html.id(select_name),
                      /* :: */[
                        Tea_html.name(select_name),
                        /* [] */0
                      ]
                    ], List.map((function (param) {
                            var name = param[0];
                            return Tea_html.option$prime(undefined, undefined, /* :: */[
                                        Tea_html.value(name),
                                        /* :: */[
                                          Tea_html.Attributes.selected(param[1]),
                                          /* [] */0
                                        ]
                                      ], /* :: */[
                                        Tea_html.text(name),
                                        /* [] */0
                                      ]);
                          }), options)),
                /* [] */0
              ]
            ]);
}

function labeled_tz_select(select_name, user_tz) {
  return labeled_select(select_name, List.map((function (tzname) {
                    return /* tuple */[
                            tzname,
                            user_tz !== undefined ? $$String.equal(user_tz, tzname) : false
                          ];
                  }), Gen_tz.tz_labels));
}

function form_block(body) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("formBlock"),
              /* [] */0
            ], body);
}

export {
  labeled_input ,
  labeled_select ,
  labeled_tz_select ,
  form_block ,
  
}
/* Tea_html Not a pure module */
