// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Common from "./common.bs.js";
import * as Tea_app from "bucklescript-tea/src-ocaml/tea_app.js";
import * as Tea_html from "bucklescript-tea/src-ocaml/tea_html.js";

function init(tz) {
  if (tz === "") {
    return {
            user_tz: undefined
          };
  } else {
    return {
            user_tz: tz
          };
  }
}

function update(model, param) {
  return model;
}

function view(model) {
  return Tea_html.form(undefined, undefined, /* :: */[
              Tea_html.method$prime("post"),
              /* :: */[
                Tea_html.action("/event/new"),
                /* [] */0
              ]
            ], /* :: */[
              Common.form_block(/* :: */[
                    Common.labeled_input("Summary", /* [] */0),
                    /* :: */[
                      Common.labeled_input("Date", /* :: */[
                            Tea_html.type$prime("date"),
                            /* [] */0
                          ]),
                      /* :: */[
                        Common.labeled_input("Start Time", /* :: */[
                              Tea_html.type$prime("time"),
                              /* [] */0
                            ]),
                        /* :: */[
                          Common.labeled_input("End Time", /* :: */[
                                Tea_html.type$prime("time"),
                                /* [] */0
                              ]),
                          /* :: */[
                            Common.labeled_tz_select("Time Zone", model.user_tz),
                            /* :: */[
                              Common.labeled_select("Repeats", /* :: */[
                                    /* tuple */[
                                      "Never",
                                      true
                                    ],
                                    List.map((function (name) {
                                            return /* tuple */[
                                                    name,
                                                    false
                                                  ];
                                          }), /* :: */[
                                          "Daily",
                                          /* :: */[
                                            "Weekly",
                                            /* :: */[
                                              "Monthly",
                                              /* :: */[
                                                "Yearly",
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ])
                                  ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]),
              /* :: */[
                Tea_html.button(undefined, undefined, /* :: */[
                      Tea_html.type$prime("submit"),
                      /* [] */0
                    ], /* :: */[
                      Tea_html.text("Create"),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]);
}

function main(user_tz) {
  var partial_arg_model = init(user_tz);
  var partial_arg = {
    model: partial_arg_model,
    update: update,
    view: view
  };
  return (function (param, param$1) {
      return Tea_app.beginnerProgram(partial_arg, param, param$1);
    });
}

export {
  init ,
  update ,
  view ,
  main ,
  
}
/* Common Not a pure module */
